from dataclasses import dataclass, field
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path
import xml.etree.ElementTree as ET


@dataclass(frozen=True)
class ExistingFeedItem:
    """Representation of an item already present in a generated RSS feed."""

    guid: str
    title: str
    link: str
    published: datetime | None = None
    description: str | None = None
    author: str | None = None
    category: list[str] = field(default_factory=list)

    @property
    def id(self) -> str:
        """Return the RSS GUID as the item's stable identity."""
        return self.guid


class ExistingFeedReader:
    """Read items from an RSS feed previously generated by the application."""

    def read(self, path: Path) -> list[ExistingFeedItem]:
        """Read existing RSS items from disk."""

        if not path.exists():
            return []

        tree = ET.parse(path)
        root = tree.getroot()

        items: list[ExistingFeedItem] = []

        for item in root.findall("./channel/item"):
            guid = self._required_text(item, "guid")

            if guid is None:
                continue

            title = self._required_text(item, "title")
            link = self._required_text(item, "link")

            if title is None or link is None:
                continue

            published = self._parse_date(
                item.findtext("pubDate")
            )

            description = self._optional_text(
                item.findtext("description")
            )

            author = self._optional_text(
                item.findtext("author")
            )

            categories = [
                category.text.strip()
                for category in item.findall("category")
                if category.text and category.text.strip()
            ]

            items.append(
                ExistingFeedItem(
                    guid=guid,
                    title=title,
                    link=link,
                    published=published,
                    description=description,
                    author=author,
                    category=categories,
                )
            )

        return items

    @staticmethod
    def _required_text(
        element: ET.Element,
        name: str,
    ) -> str | None:
        value = element.findtext(name)

        if value is None:
            return None

        value = value.strip()

        return value or None

    @staticmethod
    def _optional_text(
        value: str | None,
    ) -> str | None:
        if value is None:
            return None

        value = value.strip()

        return value or None

    @staticmethod
    def _parse_date(
        value: str | None,
    ) -> datetime | None:
        if not value:
            return None

        try:
            parsed = parsedate_to_datetime(value)
        except (TypeError, ValueError):
            return None

        if parsed.tzinfo is None:
            return parsed.replace(
                tzinfo=timezone.utc,
            )

        return parsed.astimezone(timezone.utc)